name: Tests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - website/**

jobs:
  test:
    name: Tests
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Installation
        run: yarn
      - name: Test
        run: yarn test
      - name: TypeCheck website
        run: yarn workspace website tsc
  windows-test:
    name: Windows Tests
    timeout-minutes: 30
    runs-on: windows-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Installation
        run: yarn || yarn || yarn # 3 attempts to avoid timeout errors...
      - name: Docusaurus Jest Tests
        run: yarn test
      - name: Docusaurus Build
        run: yarn build:website --locale en
        env:
          CI: true
